baseURL = "/"
languageCode = "fr"
title = "Tribulations Photographiques"
theme = "castanet"
googleAnalytics = "UA-141127036-1"
#disqusShortname = ""
themesdir = "themes/"
paginate = "9"

[permalinks]
	# page = "/:filename/"
	about = "/:filename/"
	episode = "/:filename/"


# The theme supports menus with up to one submenu per menu item
# The menu name must be "Main"
# The menus are sorted based upon their identifier
[[Menu.Main]]
    name = "A propos"
    identifier = "about"
    url = "about"

[[Menu.Main]]
    name = "Contact"
    identifier = "contact"
    url = "contact"

#[[Menu.Main]]
#    name = "Hosts"
#    identifier = "hosts"
#    url = "host"

#[[Menu.Main]]
#    name = "Guests"
#    identifier = "guests"
#    url = "guest"

#[[Menu.Main]]
#    name = "Resources"
#    identifier = "resources"
#    url = "#!"

#[[Menu.Main]]
#    name = "Books"
#    identifier = "books"
#    url = "books"
#    parent = "resources"
#[[Menu.Main]]
#    name = "Podcasts"
#    identifier = "podcasts"
#    url = "books"
#    parent = "resources"

[params]
site_theme = "grey"
site_layout = "grid"
# site_layout = "row"
enable_jumbo = "true"
# enable_jumbo = "false"
# truncate = "100"
about_logo = "img/logo_podcast.jpg"
copyright_notice = "Copyright 2018-2019 [Thomas Chauvin](https://www.thomaschauvin.com)"
itunes_subscribe = "https://itunes.apple.com/fr/podcast/tribulations-photographiques/id1436894828?l=fr"
android_subscribe = "https://www.subscribeonandroid.com/www.tribulationsphotographiques.com/feed/podcast"
spotify_subscribe = "https://open.spotify.com/show/4pWbgGvHLgWefyjlqlsy8h"
#google_play_subscribe = "https://goo.gl/app/playmusic?ibi=com.google.PlayMusic&isi=691797987&ius=googleplaymusic&link=https://play.google.com/music/m/Ihj4yege3lfmp3vs5yoopgxijpi?t%3DArrested_DevOps"
stitcher_subscribe = "https://www.stitcher.com/podcast/tribulations-photographiques?refid=stpr"
#soundcloud_subscribe = "http://feeds.soundcloud.com/users/soundcloud:users:203144248/sounds.rss"
pocketcasts_subscribe = "https://pca.st/6l27"
#mailchimp_subscribe = "//arresteddevops.us3.list-manage.com/subscribe/post?u=5e4cbcac996bb9df25f970a89&amp;id=154fa76bcc"
rss_subscribe = "https://www.spreaker.com/show/3163729/episodes/feed" #only set this if you don't want to use the built-in feed
description = "Tribulations Photographiques est un podcast francophone consacré à la photographie."
media_prefix = "https://api.spreaker.com/v2/episodes/"
  [params.feed]
    copyright = "Copyright 2018 Thomas Chauvin" #do not use markdown in this field; it is used in the feed
    itunes_subtitle = "Tribulations Photographiques est un podcast francophone consacré à la photographie. J'ai voulu créer Tribulations Photographiques pour partager avec vous mes diverses expériences, mes tribulations ainsi que mes derniers coups de cœur." #no markdown or HTML
    itunes_author = "Thomas Chauvin" #no markdown or HTML
    itunes_summary = "Tribulations Photographiques est un podcast francophone consacré à la photographie. J'ai voulu créer Tribulations Photographiques pour partager avec vous mes diverses expériences, mes tribulations ainsi que mes derniers coups de cœur." # Limited to 4000 characters or less, plain text, no HTML
    itunes_owner_name = "Thomas Chauvin"
    itunes_owner_email = "podcast@thomaschauvin.com" #contains the e-mail address that will be used to contact the owner of the Podcast for communication specifically about their Podcast on iTunes. It will not be publicly displayed on iTunes.
    itunes_image = "https://www.tribulationsphotographiques.com/static/img/logo_podcast.jpg" #fqdn to the image art for your podcast
    itunes_top_category = "Visual Arts"
    itunes_first_sub_category = ""
    itunes_second_sub_category = ""
    language = "fr-fr"

  [params.social]
    facebook = "tribulationsphotographiques"
#    facebook_admin = ["500557137","1234"] # This needs to be one or more page admins to get domain insights
    twitter = "tribulationsp"
    twitter_domain = "tribulationsphotographiques.com" # This domain shows in twitter cards as "View on `twitter_domain`"
#    googleplus = "ArrestedDevOps"
    pinterest = "thomaschauvin"
    instagram = "tribulations_photographiques"
    youtube = "channel/UCrcH3UDWzcTiMsbUFceARhg"
#    linkedin = "mattstratton"

  [params.authors]
    [params.authors.Matt]
#      name	= "Matt Stratton"
      thumbnail = "img/logo_podcast.jpg"
#      bio = "Matt Stratton is a solutions architect at Chef, where he demonstrates how Chef’s automation platform provides speed and flexibility to clients’ infrastructure. He is devoted to concepts like Continuous Delivery and Infrastructure as Code, and his license plate actually says “DevOps”. He lives in Chicago and has an unhealthy obsession with Doctor Who, Firefly, and Game of Thrones. And whiskey."
#      [params.authors.Matt.social]
#        github = "mattstratton"
#        facebook = "matt.stratton"
#        twitter = "mattstratton"
#        linkedin = "mattstratton"
#        homepage = "https://www.mattstratton.io"
#        pinterest = "mattstratton"
#        instagram = "instagram"
#        youtube = "mattstratton"
#    [params.authors.Trevor]
#			name = "Tribulations Photographiques"
#			thumbnail = "img/default.png"
#			bio = ""
#				[params.authors.Trevor.social]
#					twitter = "trevorghess"
#    [params.authors.Bridget]
#      name = "Bridget Kromhout"
#      thumbnail = "https://www.arresteddevops.com/img/Bridget.png"
#      bio = ""
#      [params.authors.Bridget.social]
#        twitter = "bridgetkromhout"

#    [params.links]
#      [params.links.ado]
#       name = "Arrested DevOps"
#        url = "https://www.arresteddevops.com"
#      [params.links.ffs]
#        name = "Food Fight Show"
#        url = "https://foodfightshow.org"
#      [params.links.sdt]
#        name = "Software Defined Talk"
#        url = "https://cote.io/podcasts/sdt/"
